FROM python:3.12.4-slim

WORKDIR /api

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy dependency files
COPY requirements.lock pyproject.toml ./

# Copy project files
COPY . .

# Install dependencies using uv
RUN uv pip install --system -r requirements.lock

EXPOSE 8000

CMD ["fastapi", "run", "api/main.py", "--port", "8000"]
