FROM python:3.12.4-slim

WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy dependency files
COPY requirements.lock pyproject.toml ./

# Copy app files
COPY /app/main.py /app/

# Install dependencies using uv
RUN uv pip install --system -r requirements.lock

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port", "8501"]
